export const REMIX_TO_LUCIDE_MAP = {
  // Navigation & Chevrons
  riArrowRightSLine: 'ChevronRight',
  riArrowLeftSLine: 'ChevronLeft',
  riArrowDownSLine: 'ChevronDown',
  riArrowUpSLine: 'ChevronUp',
  riArrowDropDownLine: 'ChevronDown',
  riArrowRightLine: 'ArrowRight',
  riArrowLeftLine: 'ArrowLeft',
  riArrowUpDownLine: 'ArrowUpDown',
  riArrowLeftRightLine: 'ArrowLeftRight',
  riArrowRightUpLine: 'ArrowUpRight',
  riArrowGoBackLine: 'Undo2',
  riArrowGoForwardLine: 'Redo2',
  right: 'ArrowRight',

  // Actions & CRUD
  riAddLine: 'Plus',
  riDeleteBin7Line: 'Trash2',
  riCloseLine: 'X',
  riCloseCircleLine: 'XCircle',
  riCheckLine: 'Check',
  riCheckDoubleLine: 'CheckCheck',
  riFileCopyLine: 'Copy',
  riPencilLine: 'Pencil',
  riSearch2Line: 'Search',
  riRefreshLine: 'RotateCw',
  riRefreshFill: 'RotateCw',
  riRestartLine: 'RotateCcw',
  riRepeat2Line: 'Repeat',
  riSaveLine: 'Save',
  riShareLine: 'Share2',
  riFilter2Line: 'Filter',
  riDownloadLine: 'Download',
  riDownloadCloud2Line: 'CloudDownload',
  riFileUploadLine: 'Upload',
  riUploadLine: 'Upload',
  riUploadCloud2Line: 'CloudUpload',
  riFileDownloadLine: 'Download',
  riPlayLine: 'Play',
  riPauseLine: 'Pause',
  riStopLine: 'Square',
  riRecordCircleLine: 'Disc',
  riRecordCircleFill: 'CircleDot',

  // Workflow Blocks & Core Entities
  riFlashlightLine: 'Zap',
  riCommandLine: 'Terminal',
  riGlobalLine: 'Globe',
  riEarthLine: 'Globe',
  riTimeLine: 'Clock',
  riTimerLine: 'Timer',
  riTimerFlashLine: 'Timer',
  riHardDrive2Line: 'HardDrive',
  riDatabase2Line: 'Database',
  riFolderLine: 'Folder',
  riFolderOpenLine: 'FolderOpen',
  riFolderZipLine: 'FolderArchive',
  riFileLine: 'File',
  riFileTextLine: 'FileText',
  riFileEditLine: 'FileEdit',
  riFileHistoryLine: 'History',
  riFileShredLine: 'FileX',
  riFileListLine: 'ListOrdered',
  riCursorLine: 'MousePointer',
  riMouseLine: 'Mouse',
  riInputCursorMove: 'TextCursor',
  riKey: 'Key',
  riKey2Line: 'Key',
  riLock2Line: 'Lock',
  riTable2: 'Table',
  riCodeSSlashLine: 'Code2',
  riBracketsLine: 'Brackets',
  riFlowChart: 'GitFork',
  riMindMap: 'Network',
  riEqualizerLine: 'Sliders',
  riSettings3Line: 'Settings',
  riPushpin2Line: 'Pin',
  riPushpin2Fill: 'Pin',
  riInformationLine: 'Info',
  riErrorWarningLine: 'AlertTriangle',
  riAlertLine: 'AlertCircle',
  riShieldKeyholeLine: 'ShieldCheck',
  riShieldLine: 'Shield',
  riCalendarLine: 'Calendar',
  riChat3Line: 'MessageSquare',
  riClipboardLine: 'Clipboard',
  riCompass3Line: 'Compass',
  riComputerLine: 'Monitor',
  riEyeLine: 'Eye',
  riEyeOffLine: 'EyeOff',
  riFlagLine: 'Flag',
  riFocus3Line: 'Crosshair',
  riFocusLine: 'Target',
  riGroupLine: 'Users',
  riTeamLine: 'Users',
  riGuideLine: 'Compass',
  riHome5Line: 'Home',
  riHtml5Line: 'FileCode',
  riImageLine: 'Image',
  riIncreaseDecreaseLine: 'TrendingUp',
  riKeyboardLine: 'Keyboard',
  riLightbulbLine: 'Lightbulb',
  riLightbulbFlashLine: 'Lightbulb',
  riLink: 'Link',
  riLinkM: 'Link',
  riLinksLine: 'Link2',
  riLinkUnlinkM: 'Unlink',
  riListUnordered: 'List',
  riMagicLine: 'Wand2',
  riMoreLine: 'MoreHorizontal',
  riMore2Line: 'MoreVertical',
  riNotification3Line: 'Bell',
  riSliceLine: 'Scissors',
  riSortAsc: 'ArrowUpNarrowWide',
  riSortDesc: 'ArrowDownWideNarrow',
  riToggleLine: 'ToggleLeft',
  riToggleFill: 'ToggleRight',
  riUser3Line: 'User',
  riUserLine: 'User',
  riWindowLine: 'AppWindow',
  riWindow2Line: 'AppWindow',
  riBaseStationLine: 'Radio',
  riBug2Line: 'Bug',
  riBrush2Line: 'Paintbrush',
  riBook3Line: 'BookOpen',
  riArticleLine: 'Newspaper',
  riDragDropLine: 'Move',
  riDragMoveLine: 'Move',
  riDriveLine: 'HardDrive',
  riDriveFill: 'HardDrive',
  riEditBoxLine: 'Edit',
  riExternalLinkLine: 'ExternalLink',
  riFullscreenLine: 'Maximize2',
  riHandHeartLine: 'HeartHandshake',
  riHistoryLine: 'History',
  riLoader2Line: 'Loader2',
  riLoginCircleLine: 'LogIn',
  riLogoutCircleRLine: 'LogOut',
  riSideBarLine: 'PanelLeft',
  riSideBarFill: 'PanelLeftClose',
  riTBoxLine: 'Type',
  riFontSize2: 'CaseSensitive',
  riCheckboxCircleLine: 'CheckCircle2',

  // Formatting / WYSIWYG
  riBold: 'Bold',
  riItalic: 'Italic',
  riH1: 'Heading1',
  riH2: 'Heading2',
  riStrikethrough2: 'Strikethrough',
  riParagraph: 'Pilcrow',
  riDoubleQuotesL: 'Quote',
  riAB: 'CaseSensitive',

  // Social / Brands
  riGithubFill: 'Github',
  riTwitterLine: 'Twitter',
  riDiscordLine: 'MessageCircle',
  riYoutubeLine: 'Youtube',

  // Custom MDI mappings
  mdiDrag: 'GripVertical',
  mdiDragHorizontal: 'GripHorizontal',
  mdiCookieOutline: 'Cookie',
  mdiCursorDefaultClickOutline: 'MousePointerClick',
  mdiGoogleSheet: 'FileSpreadsheet',
  mdiPackageVariantClosed: 'Package',
  mdiRegex: 'Regex',
  mdiEqual: 'Equal',
  mdiVariable: 'Variable',
  webhookIcon: 'Webhook',
};

export function resolveLucideIconName(name) {
  if (!name) return 'HelpCircle';
  if (REMIX_TO_LUCIDE_MAP[name]) return REMIX_TO_LUCIDE_MAP[name];
  return name;
}
